defaults:
    - tdmpc2
    - _self_

# environment
task: ms-pick-place-semi
obs: state
obs_save: rgb
num_envs: 1
sim_backend: gpu

# evaluation
checkpoint: /hard_data/user_dataset/huangliqi_dataset/demo3/Maniskill3/PickCube.pt
eval_episodes: 20
# saving
save_trajectory: true
success_only: true
log_path: /hard_data/user_dataset/huangliqi_dataset/demo3/demos/ms-pick-place-semi
save_video: true

# misc
render_obs: false
compile: false
add_text: false
